# Docker compose for:
# - Data Ingestion Container
# - MongoDB Container
# Build and execution on local machine (WSL) with:
# (1) Set environment variable in Dockerfile:
#     ENV HTTPS_PROXY=$https_proxy
# (2) docker-compose build --build-arg "https_proxy=$https_proxy"
# (3) docker-compose up

version: '3.7'
services:
  data-fetch-app:
    build: ./data_fetch
    depends_on:
      - mongodb
  etl-app:
    build: ./etl
    depends_on:
      - mongodb
      - mysql
  mongodb:
    build: ./mongodb
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped  
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dba
      MYSQL_PASSWORD: "A1YTsqilzHkUQ4"
      MYSQL_DATABASE: data_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  metabase:
    build: ./metabase
    container_name: metabase
    ports:
      - "3000:3000"
    volumes: 
      - metabase-data:/data
volumes:
  mgdbdata:  
  mysql-data:
  metabase-data:
